### ISSUE TITLE
Does not run on Linux, libz.so.1: version ZLIB_1.2.9 not found

### ISSUE THREAD

**Issue by probonopd** [DFRobot/uPyCraft#30]
On `xubuntu-18.04-desktop-amd64.iso`, getting

```
me@host:~$ '/home/me/Downloads/uPyCraft_linux_V1.0'
Traceback (most recent call last):
  File "uPyCraft.py", line 2, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /tmp/_MEIrooXex/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[8864] Failed to execute script uPyCraft

me@host:~$ '/home/me/Downloads/uPyCraft_linux_V0.30'
Traceback (most recent call last):
  File "uPyCraft.py", line 2, in <module>
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /tmp/_MEIk86I33/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[8913] Failed to execute script uPyCraft

```

**Comment by crisconru** [comment]
I've got the same problem in Elementary OS (Ubuntu 18.04)

**Comment by leozlee** [comment]
Does anyone how to deal with it?

**Comment by probonopd** [comment]
Build on trusty or xenial, but not on a newer OS version.

**Comment by bepstein111** [comment]
Same problem on Xubuntu 19.04...sighhhh

**Comment by mf-1** [comment]
Same on Ubuntu 19.10

Even a newer version is still available...

```
$ apt-file search libz.so.1   
insync: /usr/lib/insync/libz.so.1         
lib32z1: /usr/lib32/libz.so.1
lib32z1: /usr/lib32/libz.so.1.2.11
libx32z1: /usr/libx32/libz.so.1
libx32z1: /usr/libx32/libz.so.1.2.11
libzadc4: /usr/lib/x86_64-linux-gnu/genwqe/libz.so.1
zlib1g: /lib/x86_64-linux-gnu/libz.so.1
zlib1g: /lib/x86_64-linux-gnu/libz.so.1.2.11
```

**Comment by mohitchaniyal** [comment]
anyone fixed the issue
