### ISSUE TITLE
macOS version doesn't work with incorrect filename

### ISSUE THREAD

**Issue by todocono** [DFRobot/uPyCraft#33]
macOS 10.14.1 crashes after starting it. If I log in and run the file, I can read the following error

`Last login: Wed Apr  3 13:19:48 on ttys002
/Applications/uPyCraft.app/Contents/MacOS/uPyCraft ; exit;
Rudi-6:~ rc3412$ /Applications/uPyCraft.app/Contents/MacOS/uPyCraft ; exit;
/Users/rc3412
/Users/rc3412/AppData/Local/uPyCraft/temp/
/Users/rc3412/AppData/Local/uPyCraft/examples
Traceback (most recent call last):
  File "uPyCraft.py", line 2835, in <module>
  File "uPyCraft.py", line 87, in __init__
  File "uPyCraft.py", line 202, in setFont
NotADirectoryError: [Errno 20] Not a directory: '/Users/rc3412/Library/Fonts'
[24130] Failed to execute script uPyCraft
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...71 completed.

[Process completed]
`

I deleted a file called Fonts and the program exectured, prompting me to install a font. Weird enough but I made it run...

**Comment by bromanoff** [comment]
I have the same issue. The program asks me to install the font 'SourceCodePro'. After doing so, the app crashes after starting. When deleting the font, the app runs again prompting the same message.
